dist: trusty
language: rust
services: docker
sudo: required

rust: stable

env:
  global:
    - CRATE_NAME=fingers
    - DEPLOY_VERSION=stable
    - TARGET=x86_64-unknown-linux-gnu
    - OPENSSL_INCLUDE_DIR=/usr/include/openssl

matrix:
  exclude:
    - language: rust
  include:
    # Linux
    - env:
        - TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libssl-dev
    - env:
        - TARGET=i686-unknown-linux-musl
      addons:
        apt:
          packages:
            - libssl-dev
    - env:
        - TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libssl-dev
    - env:
        - TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
            - libssl-dev

    # OSX
    - env:
        - TARGET=i686-apple-darwin
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
      os: osx
      before_install:
        - brew update
        - brew install openssl
    - env:
        - TARGET=x86_64-apple-darwin
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
      os: osx
      before_install:
        - brew update
        - brew install openssl

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "kp8TDTqUY3VELkUfx0jr67u6T/IXNuqUCoTtrKOR6C2qX7dGo2CGIXweq9ugnGwHuYrQd5FjHKj0YLtlYKc79dINgfsfEhfQ4ijMylpgusldZzHNax5dYkRTXUIS7yd/kfq0dRnX/hWcJEatA+wFwp+93H7IJI8GFlPUsYvrW6HDzlAo5JZKYUSQN3aSJw34QAmOICvxU9LPtPyNHbzQ3OFazg77GDPg8GIzvdIyTL7VQk1vJRLYeNqicVAEnpMUkbLdMlgLFIDdzOM3X9q9e5ci9mBCwO7TYwsMWw0JtmtBSOMBr44E1mgk21/b/8+z2D0cSyoJJXXGcX6BrtgOIV8UJKniCAx7kpvlbb3mtvUcYdMlvxbygSju9h8SHrWROtzZwVUudSEyDKig/fg2iVvVzIN9QsoGHKqYSyP8WtkBtwLkj9dJfmQCZS7uVu1iCE2ofeIpHtE3KgkZolLd+P9a42H4Dw0pkWXIl/qnd9Eff5tNlszTlw3ljExZt0MxaNO9DXCZXaJjgYIqOqyDNqs8/13P11E8VRRn8NAPLwyxqkvn+1SfuMrdRyIkdPjOJ9xt1NK7w3uC9Lznyb3z916S2V8jp1/Zb1Bi1prse2o9fxelKERIyOlOSvmWGvoODDeI1XnMg/EYBOK/1UwFtuAS3d7V0I9TOF83sFvyxqY="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = $DEPLOY_VERSION
    tags: true
    all_branches: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never


language: rust
cache: cargo
